# Archivo de configuración de GitHub Actions
# Automatiza la ejecución del script de noticias cada 5 minutos o manualmente

name: Noticias automáticas   # Nombre visible del workflow en GitHub

on:
  schedule:
    # 06:00 UTC es igual a las 07:00 AM en España (invierno)
    - cron: '0 6 * * *' 
  workflow_dispatch: # Esto permite que sigas probando el botón manual

jobs:
  run:                         # Define el trabajo principal
    runs-on: ubuntu-latest     # Usa un contenedor Ubuntu como entorno

    steps:
      - uses: actions/checkout@v4          # Descarga el código del repositorio
      - uses: actions/setup-python@v5      # Instala Python
        with:
          python-version: "3.12"           # Versión específica de Python

      - run: pip install -r requirements.txt  # Instala dependencias del proyecto

      - name: Ejecutar recolector
        env:
          # Estas líneas conectan los Secrets de GitHub con tu código Python
          SMTP_PASS: ${{ secrets.SMTP_PASS }}
          SMTP_USER: ${{ secrets.SMTP_USER }}  # <--- ESTA ES LA QUE FALTA
          SMTP_HOST: ${{ secrets.SMTP_HOST }}
          SMTP_PORT: ${{ secrets.SMTP_PORT }}
        run: python marca_harvester.py
